name: Docker Build and Push

on: workflow_call

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}


    - name: Set Docker image name
      id: set-image-name
      run: echo "::set-output name=image_name::${{ secrets.DOCKER_HUB_USER }}/${{ github.repository }}##*/"

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.set-image-name.outputs.image_name }}:latest
