name: Python 3.8 Workflow
on: [push]

jobs:
  lint:
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/flake8.yaml@master
    
  test:
    needs: lint
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/pytest.yaml@master

  publish:
    needs: test
    uses: PedroHPAlmeida/actions-workflows-docker/.github/workflows/docker-publish.yaml@master
    secrets: inherit

  deploy:
    needs: publish
    uses: ./.github/workflows/deploy-beanstalk.yaml
    secrets: inherit
