name: Python 3.8 Workflow
on: [push]

jobs:
  lint:
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/flake8.yaml@master
    
  test:
    needs: lint
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/pytest.yaml@master

  publish:
    if: ${{ github.ref_name == 'master' || github.ref_name == 'develop'}}
    needs: test
    runs-on: ubuntu-latest
    
    outputs:
      image-name: ${{ steps.set-image-name.outputs.image-name }}

    steps:
      - name: Set Docker image name
        id: set-image-name
        run: |
          OWNER_AND_REPO=${{ github.repository }}
          REPO_NAME=$(echo "$OWNER_AND_REPO" | cut -d'/' -f2)
          echo "image-name=${{ secrets.DOCKER_HUB_USER }}/${REPO_NAME}:${{ github.ref_name }}-${{ github.sha }}" >> $GITHUB_OUTPUT
      
      - name: Publish docker image
        uses: PedroHPAlmeida/actions-workflows-docker/.github/workflows/docker-publish.yaml@master
        secrets: inherit
        with:
          image-name: ${{ steps.set-image-name.outputs.image-name }}

  deploy:
    if: ${{ github.ref_name == 'master' }}
    needs: publish
    uses: PedroHPAlmeida/actions-workflows-aws/.github/workflows/beanstalk.yaml@master
    secrets: inherit
    with:
      docker-image: ${{ needs.publish.outputs.image-name }}
      container-port: 8080
