name: Python 3.8 Workflow
on: [push]

jobs:
  # setup:
  #   uses: ./.github/workflows/setup-python3.8.yaml

  lint:
    # needs: setup
    uses: ./.github/workflows/flake8.yaml

  test:
    needs: lint
    uses: ./.github/workflows/pytest.yaml
    
  publish:
    needs: test
    uses: ./.github/workflows/docker-publish.yaml
    secrets: inherit
