name: Python 3.8 Workflow
on: [push]

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    steps:
      - uses: PedroHPAlmeida/prerequisites-action@v0.7
        with:
          DEFAULT_BRANCH: 'master'
          BRANCHES: 'develop'
          PAT_GITHUB: ${{ secrets.PAT_GITHUB_TOKEN }}

  lint:
    needs: prerequisites
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/flake8.yaml@master
    
  test:
    needs: lint
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/pytest.yaml@master

  publish:
    uses: PedroHPAlmeida/actions-workflows-docker/.github/workflows/docker-publish.yaml@master
    if: ${{ github.ref_name == 'master' || github.ref_name == 'develop'}}
    needs: test
    with:
      docker_hub_user: ${{ vars.DOCKER_HUB_USER }}
    secrets:
      docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}

  deploy:
    if: ${{ github.ref_name == 'master' }}
    needs: publish
    uses: PedroHPAlmeida/actions-workflows-aws/.github/workflows/beanstalk.yaml@master
    secrets:
      aws_key_id: ${{ secrets.AWS_KEY_ID }}
      aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
      aws_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
    with:
      docker-image: ${{ needs.publish.outputs.image_name }}
      container-port: 8080
