name: Python 3.8 Workflow
on: [push]

jobs:
  lint:
    uses: ./.github/workflows/flake8.yaml

  test:
    needs: lint
    uses: ./.github/workflows/pytest.yaml
    
  publish:
    needs: test
    uses: ./.github/workflows/docker-publish.yaml
    secrets: inherit
