name: Python 3.8 Workflow
on: [push]

jobs:
  lint:
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/flake8.yaml@master
    
  test:
    needs: lint
    uses: PedroHPAlmeida/actions-workflows-python/.github/workflows/pytest.yaml@master

  publish:
    uses: PedroHPAlmeida/actions-workflows-docker/.github/workflows/docker-publish.yaml@master
    if: ${{ github.ref_name == 'master' || github.ref_name == 'develop'}}
    needs: test
    secrets: inherit

  deploy:
    if: ${{ github.ref_name == 'master' }}
    needs: publish
    uses: PedroHPAlmeida/actions-workflows-aws/.github/workflows/beanstalk.yaml@master
    secrets: inherit
    with:
      docker-image: ${{ jobs.publish.outputs.image }}
      container-port: 8080
